### ISSUE TITLE
`pip install asreview-notes-export` gives error message

### ISSUE THREAD

**Issue by franzprante** [rohitgarud/asreview-notes-export#8]
`pip install asreview-notes-export` leads to the following error message: 
```
ERROR: Could not find a version that satisfies the requirement asreview-notes-export (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6)
ERROR: No matching distribution found for asreview-notes-export
```
Using ASReview Version 1.1.1. on macOS Ventura 13.1 

The extension looks very promising, would love to try it out!
Thanks

**Comment by rohitgarud** [comment]
Hi, @franzprante Thank you for notifying me. I am not sure what is the reason behind this issue as I was able to install it using `pip install asreview-notes-export` in a newly created virtual environment, even though I didn't have asreview installed.. I will look into it and get back to you..

**Comment by rohitgarud** [comment]
One thing to note that this functionality will soon be part of asreview as I am working on it with the ASReview team, the PR is under review.. so this extension will not be required once the change is incorporated in the asreview core and asreview version is upgraded

**Comment by franzprante** [comment]
Thanks @rohitgarud , 

installing directly from GitHub unfortunatlely also did not work for me. Maybe the problem is in my setup then.

For now, I'll revert to using the Python API for exporting notes. But I look forward to the functionality being implemented in ASReview directly.

**Comment by rohitgarud** [comment]
@franzprante You can try upgrading pip using `pip install --upgrade pip`.. and what is you Python version, I did not explicitly test the compatibility with all the Python versions and the extension was developed using Python 3.11.. that might be the source of problem. As the error mentions 0.0.1 to 0.0.6 pip is aware of the extension just couldn't find version compatible with your Python version

**Comment by rohitgarud** [comment]
Try cloning the repository using git clone and then installing using `pip install .` and there is always some issue with backslashes and forward slashes, I am using windows so that might be possible source of the issue

**Comment by deelobo** [comment]
Hello @rohitgarud I'm also having the same issue. I've tried all the steps above in a new virtual environment and got the same error message - see below. Do you know when the asreview version with the export-notes functionality will be released?  

___

Building wheels for collected packages: asreview-notes-export
  Building wheel for asreview-notes-export (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/asreviewcontrib
      creating build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/_version.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/__init__.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/entrypoint.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/notes_export.py -> build/lib/asreviewcontrib/notes_export
      UPDATING build/lib/asreviewcontrib\notes_export\_version.py
      error: [Errno 2] No such file or directory: 'build/lib/asreviewcontrib\\notes_export\\_version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asreview-notes-export
  Running setup.py clean for asreview-notes-export
Failed to build asreview-notes-export
Installing collected packages: asreview-notes-export
  Running setup.py install for asreview-notes-export ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for asreview-notes-export did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running install
      /Users/lobo0010/miniconda3/envs/asreview/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/asreviewcontrib
      creating build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/_version.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/__init__.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/entrypoint.py -> build/lib/asreviewcontrib/notes_export
      copying asreviewcontrib/notes_export/notes_export.py -> build/lib/asreviewcontrib/notes_export
      UPDATING build/lib/asreviewcontrib\notes_export\_version.py
      error: [Errno 2] No such file or directory: 'build/lib/asreviewcontrib\\notes_export\\_version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> asreview-notes-export

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by rohitgarud** [comment]
Thank you for letting me know @deelobo. May I ask if are you using Windows or Mac? So that I can pinpoint the issue being related to Mac users only.  I think `build/lib/asreviewcontrib\notes_export\_version.py` is creating issues because of the backslash and forward slash mixup.

**Comment by deelobo** [comment]
Thanks for your prompt reply, @rohitgarud  
Yeah, it worked! I'm a Mac user. Thanks a bunch.

Here are the steps I took:
1. Updated everything - python, conda, PyPi
2. Created a new conda environment
3. Installed asreview
4. Ran asreview to check if the installation worked
5. Installed asreview-notes-export using:  pip install --upgrade asreview-notes-export
6. Voilá!

**Comment by rohitgarud** [comment]
Thank you for mentioning the steps.

 @franzprante I think the issue is solved. Please check if you can install the latest version.

**Comment by franzprante** [comment]
Just tried it, it works! Thanks a lot! I am closing this.

**Comment by rohitgarud** [comment]
Thank you @franzprante. Soon it will be part of the core functionality of ASReview. The PR is already merged, notes export functionality will be added in the next release.
